/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import bazar.ClienteDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dan0001
 */
public class Clientes extends javax.swing.JInternalFrame {

    List<bazar.Cliente> listaClientes = new ArrayList();
    
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
        atualizaGrid();

    }
    
    private void atualizaGrid(){
        bazar.ClienteDAO daocliente = new ClienteDAO();
        listaClientes = daocliente.selecionarTodos();
        
        DefaultTableModel modelo = (DefaultTableModel) gridClientes.getModel();
        
        int rowCount = modelo.getRowCount();
        for(int i = rowCount - 1; i >= 0;i--){
            modelo.removeRow(i);
        }
        
        for (bazar.Cliente c : listaClientes) {
                modelo.addRow(new Object[] {c.getCodigo(), c.getNome(), c.getSobrenome(), c.getTelefone()});
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gridClientes = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();

        setClosable(true);
        setMaximizable(true);
        setMaximumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 72, 1026, 10);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 11, 160, 55);

        jButton2.setText("Alterar");
        getContentPane().add(jButton2);
        jButton2.setBounds(176, 11, 160, 55);

        jButton3.setText("Deletar");
        getContentPane().add(jButton3);
        jButton3.setBounds(342, 11, 160, 55);

        gridClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Sobrenome", "Telefone "
            }
        ));
        jScrollPane1.setViewportView(gridClientes);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 88, 1006, 493);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(0, 601, 1026, 20);

        setBounds(0, 0, 1024, 659);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastroCliente objCadastro = new CadastroCliente();
        objCadastro.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gridClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
